CREATE DATABASE IF NOT EXISTS noteweb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE noteweb;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(191) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_url MEDIUMTEXT DEFAULT NULL,
    is_activated TINYINT(1) NOT NULL DEFAULT 0,
    activation_token VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
